# Generated by Django 4.2.5 on 2023-10-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_postimage_image_alter_postimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Plant name'),
        ),
    ]
