# Generated by Django 4.2.5 on 2023-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_postimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
