# Generated by Django 4.2.5 on 2023-10-23 08:01

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_postimage_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('Tree_ID', models.CharField(max_length=127)),
                ('Species', models.CharField(max_length=127)),
                ('Common_Name', models.CharField(max_length=127)),
                ('Family', models.CharField(max_length=127)),
                ('Waypoint', models.CharField(max_length=127)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
    ]
